##-----------------------------makeCacheMatrix-------------------------------##
#makeCacheMatrix takes a square invertible matrix and returns a list of four
#functions for use in cacheSolve.R, which will retrieve the inverse. 
#
#Output:
#     set()       Allows users to change the matrix after makeCacheMatrix.R
#                 has been executed once.
#     get()       Returns the input matrix.
#     setinv()    Caches a calculated inverse in the makeCacheMatrix 
#                 environment.
#     getinv()    Retrieves inverse values from the makeCacheMatrix 
#                 environment.


#Input arguments:
# x:     a square invertible matrix that will be inverted by cacheSolve.

##-----------------------------------CODE------------------------------------##

makeCacheMatrix <- function(x = matrix()) {
      
      ## First check whether the input matrix is square and invertible. If not, 
      ## issue a warning.
      
      if (!identical(dim(x)[1],dim(x)[2])){
            warning("Matrix not square. cacheSolve.R requires a matrix of 
                    equal dimensions")
      } else if (det(x)==0){
            warning("Matrix not invertible. Input for cacheSolve.R must be 
                    non-singular.")
      }
      
      ## If input matrix is correct, first empty old cache and then define the four
      ## output functions. 
      
      inv <- NULL                   
      
      
      set <- function(y) {          # Function 1: set()
            x <<- y                 # - saves a new matrix in the makeCacheMatrix
            # environment.
            inv <<- NULL            # - empties inverse cache.
      }
      get <- function() x           # Function 2: get()
      # Returns the input matrix as stored in the
      # makeCacheMatrix environment. 
      
      setinv <- function(inverse) inv <<- inverse 
      # Function 3: setinv()
      # Caches a new inverse value in the
      # makeCacheMatrix environment.
      
      getinv <- function() inv      # Function 4: getinv()
      # Returns cached inverse values.
      
      ## Return these functions in a list. Elements of the list carry the name of
      ## the function in that element for easy reference in cacheSolve.R. 
      
      list(set = set, get = get,    
           setinv = setinv,         
           getinv = getinv)         
      
      }

##-------------------------------cacheSolve----------------------------------##

#cacheSolve returns the inverse of a square invertible matrix by using the
#solve() function and caches the value. If the function is then executed again
#on the same matrix, it immediately returns the cached value without calling
#on solve() again.

#Input arguments:
#   x:            a list generated by executing makeCacheMatrix.R on the
#                 matrix of interest, consisting of the functions set(),
#                 get(),setinv() and getinv(). See also makeCacheMatrix.R.

#...              Additional arguments will be passed to the solve()
#                 function that calculates the inverse. 

##-----------------------------------CODE------------------------------------##

cacheSolve <- function(x, ...) {
      
      ## First check for cached value:
      
      inv <- x$getinv()                   #calls on the getinv() function
      #from x.This will return the cached 
      #value (if present), or NULL if no 
      #value was known.
      
      ## If a cached value is found: inform user and return the saved value. 
      
      if(!is.null(inv)) {                 
            message("getting cached data")
            return(inv)                    
      }                                    
      
      ## If no cached value is found: retrieve matrix with get(), calculate inverse
      ## with solve(), cache value with setinv() and return the output. 
      
      data <- x$get()                                                                                       
      inv <- solve(data, ...)             
      x$setinv(inv)             
      inv                                 
      
}
